import express from 'express';
import bodyParser from 'body-parser';

import logger from './logger';
import conf from './conf';
import models from './models';
import api from './api';

const PORT = conf.get('port');
const HOST = conf.get('host');

logger.info(`initializing app with NODE_ENV=${process.env.NODE_ENV}`);

const app = express();

app.set('views', './views');
app.set('view engine', 'pug');

app.use(bodyParser.json());


//used for tests
if (conf.get('serve_static_files')) {
    app.use('/static', express.static('/static'));
}

//compile a list of css & js files to load on page
const STATIC_ASSETS = {
    js: [],
    css: []
};

app.use('/api', api);

// use webpack dev server for statics?
if (conf.get('webpack_dev_server')) {
    STATIC_ASSETS.js.push('http://localhost:3000/static/bundle.js');
//else - read manifset generated by webpack
} else {
    let manifest;
    if (conf.get('serve_static_files')) {
        manifest = require('../../static/assets.json');
    } else {
        manifest = require('../assets.json');
    }
    STATIC_ASSETS.css.push(manifest.main.css);
    STATIC_ASSETS.js.push(manifest.main.js);
}


//config to be passed to frontend
const BOOTSTRAP_CONFIG = JSON.stringify({
    'foo': 'bar'
});

app.get('*',  function (req, res) {
    res.render('index', {STATIC_ASSETS, BOOTSTRAP_CONFIG});
});


export default app;