import express from 'express';
import logger from './logger';
import conf from './conf';

const PORT = conf.get('port');
const HOST = conf.get('host');

logger.info(`initializing app with NODE_ENV=${process.env.NODE_ENV}`);
const DEV = process.env.NODE_ENV === 'development';

const app = express();

app.set('views', './views')
app.set('view engine', 'pug')


//compile a list of css & js files to load on page
const STATIC_ASSETS = {
    js: [],
    css: []
};

//dev mode - use webpack dev server
if (DEV) {
    STATIC_ASSETS.js.push('http://localhost:3000/static/bundle.js')

//else - read manifset generated by webpack
} else {
    let manifest = require('./assets.json');
    STATIC_ASSETS.css.push(manifest.main.css);
    STATIC_ASSETS.js.push(manifest.main.js);
}

app.get('*',  function (req, res) {
    res.render('index', {DEV, STATIC_ASSETS});
});


export default app;